name: google_maps_flutter_geojson
description: Fork of mateuszkulpa's Flutter package allows to display geojson data on Google Maps.
version: 1.0.0
homepage: https://github.com/mateuszkulpa

environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.6.0
  google_maps_flutter: ^2.1.10
  uuid: ^3.0.5
  
dev_dependencies:
  build_runner: ^2.1.0
  json_serializable: ^6.3.1
  
  flutter_test:
    sdk: flutter
flutter:
